Repository WebKit/MotionMark, pull requests merged in 2024-01, with the labels that each got.

#29 Use 'display' style as the default visibility property for Multiply
  MotionMark/tests/core/resources/multiply.js
Labels: non-trivial, test change

#31 Make the 'Paths' test workload more consistent
  MotionMark/tests/core/resources/canvas-tests.js
Labels: non-trivial, test change

#24 Fix instability in the Design subtest
  MotionMark/tests/core/design.html
  MotionMark/tests/core/resources/design.js
Labels: non-trivial, test change

#39 Clarify sample indexing in main.js
  MotionMark/tests/resources/main.js
Labels: trivial

#37 The first frame of each ramp has an erroneously long frame duration
  MotionMark/tests/resources/main.js
Labels: harness change

#40 Simplify regression computation
  MotionMark/resources/runner/motionmark.js
  MotionMark/resources/statistics.js
  MotionMark/tests/resources/main.js
Labels: trivial

#36 Ignore mutation frames when scoring
  MotionMark/resources/debug-runner/graph.js
  MotionMark/resources/debug-runner/motionmark.css
  MotionMark/resources/runner/motionmark.js
  MotionMark/resources/strings.js
  MotionMark/tests/resources/main.js
Labels: harness change
